---
version: '3'
services:
  master:
    build:
      context: .
      dockerfile: ./master.Dockerfile
    working_dir: /root/DockerTest/project
    volumes:
      - /c/repos/ansible/playbooks:/root/playbooks
      - /c/repos/ansible/config:/etc/ansible

    command: tail -f /dev/null

  web:
    build:
      context: .
      dockerfile: ./node.Dockerfile

  db:
    build: 
      context: .
      dockerfile: ./node.Dockerfile

  lb:
    build: 
      context: .
      dockerfile: ./node.Dockerfile
    ports:
    - 8080:80
