---
version: '3'
services:
  master:
    build:
      context: .
      dockerfile: ./master.dockerfile
    working_dir: /root/DockerTest/project
    volume:
      -/root/tp_storage:/root/tp_storage

    command: /bin/bash

  web:
    build:
      context: .
      dockerfile: ./node.Dockerfile

  db:
    build: 
      context: .
      dockerfile: ./node.Dockerfile

  lb:
    build: 
      context: .
      dockerfile: ./node.Dockerfile
    ports:
    - 8080:80
